### ISSUE TITLE
load operation bug

### ISSUE THREAD

**Issue by RainbowUnicon** [webrown/PISA#1]
If I create a cache (index bit : 2, way bit: 2, and offset bit: 2) and run sort vect program, then it crushes...
According to debug output, it says that load operation only loaded 62 elements... 
If you have time, can you check?

Thank you

**Comment by webrown** [comment]
Hi Young,
Are there any cache cases for sort vect that work?
Is sort vect currently on the repo?
Best,
-Walter

**Comment by RainbowUnicon** [comment]
Sort vect works for cache with different sizes.
Yes, I put that in awesome program!
Thanks for investifgation

**Comment by webrown** [comment]
NP!
Stupid question:  may I put in tiny changes to MemoryInterface to make them
stop popping up warnings in my compiler?
Best,
-Walter

**Comment by webrown** [comment]
Hi Young,
I think that the issue is that cache expects that it can hold the entire
capacity of the vector that is being requested.  This is a hardware
constraint as to prevent a cache that has 32 slots from magically dumping
out 64 values.  The cache described holds exactly 64 values, so if the
first index of a vector does not align with the first entry of a line, an
extra line will be needed to hold the entire vector.

I will modify the Cache's read function to iteratively  report elements.
However, just focusing on larger caches should suffice for now until I fix
this.

Best,
-Walter

**Comment by webrown** [comment]
Hi Young,
Fix pushed!  You're good 2 go!
Thanks for finding that! :D
Best,
-Walter

**Comment by RainbowUnicon** [comment]
Thank you
